update

diff --git a/playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml b/playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
--- a/playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
+++ b/playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
@@ -110,10 +110,29 @@
           cluster/kubectl.sh create clusterrolebinding --user system:serviceaccount:kube-system:cloud-controller-manager kube-system-cluster-admin-4 --clusterrole cluster-admin
           cluster/kubectl.sh create clusterrolebinding --user system:serviceaccount:kube-system:shared-informers kube-system-cluster-admin-5 --clusterrole cluster-admin
           cluster/kubectl.sh create clusterrolebinding --user system:kube-controller-manager  kube-system-cluster-admin-6 --clusterrole cluster-admin
+
           cluster/kubectl.sh create -f "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/examples/loadbalancers/external-http-nginx.yaml"
           cluster/kubectl.sh create -f "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/examples/loadbalancers/internal-http-nginx.yaml"
+          ./cluster/kubectl.sh describe services external-http-nginx-service
+          ./cluster/kubectl.sh describe services internal-http-nginx-service
+
+          external_lb_ip=$(./cluster/kubectl.sh describe services external-http-nginx-service |grep "LoadBalancer Ingress" | awk -F ' ' '{print $3}')
+          if curl http://${external_lb_ip} |grep "Welcome to nginx"
+          then
+              echo "External LB services launched sucessfully :)"
+          else
+              echo "External LB services launched failed :("
+              exit 1
+          fi
+          internal_lb_ip=$(./cluster/kubectl.sh describe services internal-http-nginx-service |grep "LoadBalancer Ingress" | awk -F ' ' '{print $3}')
+          if curl http://${internal_lb_ip} |grep "Welcome to nginx"
+          then
+              echo "Internal LB services launched sucessfully :)"
+          else
+              echo "Internal LB services launched failed :("
+              exit 1
+          fi
           popd
-          sleep 7200
         executable: /bin/bash
         chdir: '{{ zuul.project.src_dir }}'
       environment: '{{ golang_env }}'
