update k8s lb job

diff --git a/playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml b/playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
--- a/playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
+++ b/playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
@@ -1,8 +1,8 @@
 - name: Set up Kubernetes local cluster
   hosts: all
+  become: yes
   roles:
     - export-vexxhost-openrc
-  become: yes
   tasks:
     - name: Set up Kubernetes local cluster
       shell:
@@ -79,49 +79,37 @@
           cluster/kubectl.sh create clusterrolebinding --user system:kube-controller-manager  kube-system-cluster-admin-6 --clusterrole cluster-admin
 
           # Run test
-          sleep 7200
-          cluster/kubectl.sh create -f "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/examples/loadbalancers/external-http-nginx.yaml"
-          cluster/kubectl.sh create -f "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/examples/loadbalancers/internal-http-nginx.yaml"
+          for test_case in internal external
+          do
+            test_file="{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/examples/loadbalancers/${test_case}-http-nginx.yaml"
+            service_name="${test_case}-http-nginx-service"
+            # Delete fake floating-network-id to use the default one in cloud config
+            sed -i '/loadbalancer.openstack.org/d' "$test_file"
+            cluster/kubectl.sh create -f "$test_file"
 
-          for i in $(seq 1 120); do
-              if [ -z "${external_lb_ip}" ]; then
-                  external_lb_ip=$(./cluster/kubectl.sh describe services external-http-nginx-service |grep "LoadBalancer Ingress" | awk -F ' ' '{print $3}')
-              fi
-              if [ -z "${internal_lb_ip}" ]; then
-                  internal_lb_ip=$(./cluster/kubectl.sh describe services internal-http-nginx-service |grep "LoadBalancer Ingress" | awk -F ' ' '{print $3}')
-              fi
+            if ! service_name="$service_name" timeout 300 bash -c '
+                while :
+                do
+                    [[ -n $(cluster/kubectl.sh describe service "$service_name" | awk "/LoadBalancer Ingress/ {print \$3}") ]] && break
+                    sleep 1
+                done
+                '
+            then
+                echo "Timed out to wait for $test_case loadbalancer services deployment!"
+                cluster/kubectl.sh describe pods
+                cluster/kubectl.sh describe services
+                exit 1
+            fi
 
-              if [ -n "${external_lb_ip}" -a -n "${internal_lb_ip}" ]; then
-                  break
-              fi
-              echo "Waiting for deploying loadbalancer service on try ${i} ..."
-              sleep 5
+            ingress_ip=$(cluster/kubectl.sh describe service "$service_name" | awk "/LoadBalancer Ingress/ {print \$3}")
+            if curl --retry 5 --retry-max-time 30 "http://$ingress_ip" | grep 'Welcome to nginx'
+            then
+                echo "$test_case lb services launched sucessfully!"
+            else
+                echo "$test_case lb services launched failed!"
+                exit 1
+            fi
           done
-
-          if [ -z "${external_lb_ip}" -o -z "${internal_lb_ip}" ]; then
-              echo "Timed out to wait for loadbalancer services deployment!"
-              cluster/kubectl.sh describe pods
-              cluster/kubectl.sh describe services
-              exit 1
-          fi
-
-          if curl --retry 5 --retry-max-time 30 http://${external_lb_ip} |grep "Welcome to nginx"
-          then
-              echo "External LB services launched sucessfully!"
-          else
-              echo "External LB services launched failed!"
-              exit 1
-          fi
-
-          if curl --retry 5 --retry-max-time 30 http://${internal_lb_ip} |grep "Welcome to nginx"
-          then
-              echo "Internal LB services launched sucessfully!"
-          else
-              echo "Internal LB services launched failed!"
-              exit 1
-          fi
-          popd
         executable: /bin/bash
         chdir: '{{ zuul.project.src_dir }}'
       environment: '{{ golang_env | combine(vexxhost_openrc) }}'
-
