update volcano jobs

diff --git a/playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/run-volcano.yaml b/playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/run-volcano.yaml
--- a/playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/run-volcano.yaml
+++ b/playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/run-volcano.yaml
@@ -17,24 +17,6 @@
         - node
       kubeadm_join_cmd: "{{ hostvars['k8s-master']['kubeadm_join_cmd']['stdout'] }}"
 
-#- hosts: k8s-nodes
-#  become: yes
-#  roles:
-#    - config-golang
-#  tasks:
-#    - name: Debug volcano
-#      shell: |
-#        set -ex
-#        mkdir -p $GOPATH/src/volcano.sh/
-#        git clone https://github.com/volcano-sh/volcano $GOPATH/src/volcano.sh/volcano
-#        pushd $GOPATH/src/volcano.sh/volcano
-#        make images
-#        docker build example/integrations/tensorflow/ -t volcanosh/example-tf:0.0.1
-#        docker images
-#      args:
-#        executable: /bin/bash
-#      environment: '{{ global_env }}'
-
 - hosts: k8s-master
   become: yes
   roles:
@@ -46,8 +28,6 @@
         mkdir -p $GOPATH/src/volcano.sh/
         git clone https://github.com/volcano-sh/volcano $GOPATH/src/volcano.sh/volcano
         pushd $GOPATH/src/volcano.sh/volcano
-        # make images
-        # docker images
         curl -L https://git.io/get_helm.sh | bash
         helm init
         kubectl --namespace kube-system create serviceaccount tiller
@@ -65,11 +45,45 @@
         helm install installer/chart/volcano --namespace volcano-trial --name volcano-trial
         kubectl -n volcano-trial get pods
         kubectl -n volcano-trial get svc
-        # kubectl -n volcano-trial wait --timeout 300s --for condition=ready pod --all
-        # docker build example/integrations/tensorflow/ -t volcanosh/example-tf:0.0.1
-        sleep 720000
+        sleep 30
+        kubectl -n volcano-trial wait --timeout 300s --for condition=ready pod --all
+
+        # workaround
+        sed -i -e '/\  plugins:/a \    env: []' example/integrations/tensorflow/tf-example.yaml
+
         kubectl -n volcano-trial create -f example/integrations/tensorflow/
-        popd
+        kubectl -n volcano-trial get job.batch.volcano.sh
+
+        function tfjobs_status() {
+            kubectl -n volcano-trial get job.batch.volcano.sh -o jsonpath='{.items[*].status.state.phase}'|uniq
+        }
+
+        timeout 7200 bash -c '
+            while :
+            do
+                jobs_status = $(tfjobs_status)
+                if [[ ${job_status} == Running ]]; then
+                    echo "Waiting for TF jobs running..."
+                elif echo ${job_status} |grep Failed;
+                    echo "Some TFjobs has failed :("
+                    kubectl -n volcano-trial get job.batch.volcano.sh
+                    exit 1
+                elif [[ ${job_status} == Succeeded ]]; then
+                   echo "TFjobs running Succeeded :)"
+                   kubectl -n volcano-trial get job.batch.volcano.sh
+                   break
+                fi
+                sleep 30
+            done
+            '
+        mkdir -p {{ RESULTS_PATH }}/tfjobs/
+        job_pods = $(kubectl -n volcano-trial get pods -o custom-columns=NAME:.metadata.name --no-headers |grep benchmark)
+        for job_pod in ${job_pods}; do
+            kubectl -n volcano-trial logs ${job_pod} > {{ RESULTS_PATH }}/tfjobs/${job_pod}.log
+        done
+
+        kubectl -n volcano-trial delete -f example/integrations/tensorflow/
+        helm delete integration --purge
       args:
         executable: /bin/bash
         chdir: '{{ ansible_user_dir }}/workspace'
