update

diff --git a/playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication/run.yaml b/playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication/run.yaml
--- a/playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication/run.yaml
+++ b/playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication/run.yaml
@@ -144,21 +144,7 @@
           cluster/kubectl.sh create clusterrolebinding --user system:serviceaccount:kube-system:cloud-controller-manager kube-system-cluster-admin-4 --clusterrole cluster-admin
           cluster/kubectl.sh create clusterrolebinding --user system:serviceaccount:kube-system:shared-informers kube-system-cluster-admin-5 --clusterrole cluster-admin
           cluster/kubectl.sh create clusterrolebinding --user system:kube-controller-manager  kube-system-cluster-admin-6 --clusterrole cluster-admin
-          sleep 7200
-          cluster/kubectl.sh config set-cluster webhook --server=https://localhost:8443/webhook --insecure-skip-tls-verify=true
-          cluster/kubectl.sh config set-credentials webhook --auth-provider=openstack
-          cluster/kubectl.sh config set-context --cluster=webhook --user=webhook webhook@webhook
-          cluster/kubectl.sh config use-context webhook@webhook
 
-          cluster/kubectl.sh config set-credentials myself --client-key=/var/run/kubernetes/client-admin.key --client-certificate=/var/run/kubernetes/client-admin.crt
-          cluster/kubectl.sh config set-context local --cluster=local --user=myself
-          cluster/kubectl.sh config use-context local
-
-          cluster/kubectl.sh config set-credentials openstackuser --auth-provider=openstack
-          cluster/kubectl.sh config set-context --cluster=local --user=openstackuser openstackuser@local
-          cluster/kubectl.sh config use-context openstackuser@local
-          cluster/kubectl.sh create rolebinding username-view --clusterrole view --user username --namespace default
-          cluster/kubectl.sh get pods
           {
             TOKEN=$(openstack token issue -f value -c id)
             authenticated_info=`cat << EOF | curl -kvs -XPOST -d @- https://localhost:8443/webhook | python -c "import sys, json; print json.load(sys.stdin)"
@@ -187,13 +173,22 @@
               }
           }
           EOF`
-            authorization_body=$(python -c "import json; s1=${authenticated_info}; s2=${base_body}; s2['spec'].update(s1['status']['user']); print json.dumps(s2)")
-            echo $authorization_body | curl -kvs -XPOST -d @- https://localhost:8443/webhook | python -mjson.tool
+            authorization_body=$(python -c "import json; s1=${authenticated_info}; s2=${base_body}; \
+               s2['spec']['user']=s1['status']['user']['username']; \
+               s2['spec']['group']=s1['status']['user']['groups']; \
+               s2['spec']['extra']=s1['status']['user']['extra'];print json.dumps(s2)")
+            allowed=$(echo $authorization_body | curl -kvs -XPOST -d @- https://localhost:8443/webhook | python -mjson.tool)
           } 1> /dev/null 2>&1
           echo ${allowed}
 
+          cluster/kubectl.sh config set-credentials openstackuser --auth-provider=openstack
+          cluster/kubectl.sh config set-context --cluster=local --user=openstackuser openstackuser@local
+          cluster/kubectl.sh config use-context openstackuser@local
+          if ! cluster/kubectl.sh get pods; then
+              echo "Testing kubernetes+keystone authentication and authorizatio failed!"
+              exit 1
+          fi
           popd
-
         executable: /bin/bash
         chdir: '{{ zuul.project.src_dir }}'
       environment: '{{ golang_env }}'
