Update k8s flexvolume job

diff --git a/playbooks/cloud-provider-openstack-acceptance-test-flexvolume-cinder/run.yaml b/playbooks/cloud-provider-openstack-acceptance-test-flexvolume-cinder/run.yaml
--- a/playbooks/cloud-provider-openstack-acceptance-test-flexvolume-cinder/run.yaml
+++ b/playbooks/cloud-provider-openstack-acceptance-test-flexvolume-cinder/run.yaml
@@ -10,8 +10,8 @@
     - shell:
         cmd: |
           set -x
-          set -e
-          set -o pipefail
+          # set -e
+          # set -o pipefail
 
           # Create cloud-config
           source /opt/stack/new/devstack/openrc admin admin
@@ -55,8 +55,8 @@
           mkdir -p /usr/libexec/kubernetes/kubelet-plugins/volume/exec/cinder.io~cinder-flex-volume-driver/
           cp cinder-flex-volume-driver /usr/libexec/kubernetes/kubelet-plugins/volume/exec/cinder.io~cinder-flex-volume-driver/
 
-          k8s_root="$GOPATH/src/k8s.io/kubernetes"
-          kubectl="$k8s_root/cluster/kubectl.sh"
+          export k8s_root="$GOPATH/src/k8s.io/kubernetes"
+          export kubectl="$k8s_root/cluster/kubectl.sh"
           # -E preserves the current env vars, but we need to special case PATH
           sudo -E PATH=$PATH SHELLOPTS=$SHELLOPTS "$k8s_root/hack/local-up-cluster.sh" -O
 
@@ -73,6 +73,51 @@
           "$kubectl" create clusterrolebinding --user system:serviceaccount:kube-system:cloud-controller-manager kube-system-cluster-admin-4 --clusterrole cluster-admin
           "$kubectl" create clusterrolebinding --user system:serviceaccount:kube-system:shared-informers kube-system-cluster-admin-5 --clusterrole cluster-admin
           "$kubectl" create clusterrolebinding --user system:kube-controller-manager  kube-system-cluster-admin-6 --clusterrole cluster-admin
+
+          # Run test
+          VOLUME_ID=$(openstack volume create --size 1 test -f value -c id)
+          cat << EOF | "$kubectl" create -f -
+          apiVersion: v1
+          kind: Pod
+          metadata:
+            name: nginx
+            namespace: default
+          spec:
+            containers:
+            - name: nginx
+              image: nginx
+              volumeMounts:
+              - name: test
+                mountPath: /data
+              ports:
+              - containerPort: 80
+            volumes:
+            - name: test
+              flexVolume:
+                driver: "cinder.io/cinder-flex-volume-driver"
+                fsType: "ext4"
+                options:
+                  volumeID: "$VOLUME_ID"
+                  cinderConfig: "/etc/kubernetes/cloud-config"
+          EOF
+
+          # If test passed
+          if timeout 100 bash -c '
+              while :
+              do
+                  [[ $("$kubectl" describe pod nginx | awk "/^Status:/ {print \$2}") == Running ]] && break
+                  sleep 1
+              done
+              '
+          then
+              echo 'Run test successful'
+              "$kubectl" get pod nginx
+          else
+              echo 'Run test failed'
+              "$kubectl" get pod nginx
+              "$kubectl" describe pod nginx
+              # exit 1
+          fi
 
           sleep 7200
         executable: /bin/bash
