[CPO] Improve the CI job for k8s-keystone-auth webhook

diff --git a/playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml b/playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
--- a/playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
+++ b/playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
@@ -16,7 +16,7 @@
           set -o pipefail
 
           # Build cloud-provider-openstack binaries
-          make build
+          BUILD_CMDS=k8s-keystone-auth make build
 
           apt-get install python-pip -y
           pip install -U python-openstackclient
@@ -36,10 +36,6 @@
           bs-version = v3
           ignore-volume-az = yes
           EOF
-
-          cp ./examples/webhook/policy.json /etc/kubernetes/
-          sed -i "s/c1f7910086964990847dc6c8b128f63c/$OS_PROJECT_NAME/g" /etc/kubernetes/policy.json
-          sed -i -e "s/k8s-admin/admin/g" /etc/kubernetes/policy.json
 
           # Create webhook.kubeconfig
           cat << EOF >> /etc/kubernetes/webhook.kubeconfig
@@ -106,87 +102,105 @@
           pushd '{{ k8s_src_dir }}'
           sudo -E PATH=$PATH SHELLOPTS=$SHELLOPTS ./hack/local-up-cluster.sh -O
           popd
+
+          # Set up the kubeconfig
+          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
+          chmod +x ./kubectl
+          mv ./kubectl /usr/local/bin/kubectl
+          mkdir -p {{ ansible_user_dir }}/.kube
+          kubefile={{ ansible_user_dir }}/.kube/.kube/config
+          kubectl config set-cluster local --server=https://localhost:6443 --certificate-authority=/var/run/kubernetes/server-ca.crt --kubeconfig=$kubefile
+          kubectl config set-credentials myself --client-key=/var/run/kubernetes/client-admin.key --client-certificate=/var/run/kubernetes/client-admin.crt --kubeconfig=$kubefile
+          kubectl config set-context local --cluster=local --user=myself --kubeconfig=$kubefile
+          kubectl config use-context local --kubeconfig=$kubefile
+
+          # Create the initial configmaps for k8s-keystone-auth webhook
+          cat <<EOF | kubectl apply -f -
+          apiVersion: v1
+          kind: ConfigMap
+          metadata:
+            name: keystone-auth-policy
+            namespace: kube-system
+          data:
+            policies: |
+              [
+                {
+                  "users": {
+                    "projects": ["demo"],
+                    "roles": ["member"]
+                  },
+                  "resource_permissions": {
+                    "*/pods": ["get", "list", "watch", "create"]
+                  }
+                }
+              ]
+          EOF
+
+          cat <<EOF | kubectl apply -f -
+          apiVersion: v1
+          kind: ConfigMap
+          metadata:
+            name: keystone-sync-policy
+            namespace: kube-system
+          data:
+            syncConfig: |
+              role-mappings:
+                - keystone-role: member
+                  groups: ["member"]
+          EOF
+
+          # Start k8s-keystone-auth webhook service
           [[ "$OS_AUTH_URL" =~ "v3" ]] && keystone_url=${OS_AUTH_URL} || keystone_url=${OS_AUTH_URL}/v3
-          nohup ./k8s-keystone-auth \
+          nohup ./k8s-keystone-auth-amd64 \
                 --tls-cert-file /var/run/kubernetes/serving-kube-apiserver.crt \
                 --tls-private-key-file /var/run/kubernetes/serving-kube-apiserver.key \
-                --keystone-policy-file /etc/kubernetes/policy.json \
+                --policy-configmap-name keystone-auth-policy \
+                --sync-configmap-name keystone-sync-policy \
                 --log-dir=${LOG_DIR} \
                 --v=10 \
+                --kubeconfig /var/run/kubernetes/admin.kubeconfig \
                 --keystone-url ${keystone_url} >"${LOG_DIR}/keystone-auth.log" 2>&1 &
 
-          # set up the config we need for kubectl to work
-          '{{ kubectl }}' config set-cluster local --server=https://localhost:6443 --certificate-authority=/var/run/kubernetes/server-ca.crt
-          '{{ kubectl }}' config set-credentials myself --client-key=/var/run/kubernetes/client-admin.key --client-certificate=/var/run/kubernetes/client-admin.crt
-          '{{ kubectl }}' config set-context local --cluster=local --user=myself
-          '{{ kubectl }}' config use-context local
-          # Hack for RBAC for all for the new cloud-controller process, we need to do better than this
-          # It looks like we need to wait the Kubernetes services get ready before binding roles, so add a retry mechanism here
-          timeout 120 bash -c '
-              while :
-              do
-                  {{ kubectl }} create clusterrolebinding --user system:serviceaccount:kube-system:default kube-system-cluster-admin-1 --clusterrole cluster-admin && break
-                  sleep 5
-              done
-          '
-          '{{ kubectl }}' create clusterrolebinding --user system:serviceaccount:kube-system:pvl-controller kube-system-cluster-admin-2 --clusterrole cluster-admin
-          '{{ kubectl }}' create clusterrolebinding --user system:serviceaccount:kube-system:cloud-node-controller kube-system-cluster-admin-3 --clusterrole cluster-admin
-          '{{ kubectl }}' create clusterrolebinding --user system:serviceaccount:kube-system:cloud-controller-manager kube-system-cluster-admin-4 --clusterrole cluster-admin
-          '{{ kubectl }}' create clusterrolebinding --user system:serviceaccount:kube-system:shared-informers kube-system-cluster-admin-5 --clusterrole cluster-admin
-          '{{ kubectl }}' create clusterrolebinding --user system:kube-controller-manager  kube-system-cluster-admin-6 --clusterrole cluster-admin
-
-          {
-              authenticated_info=$(cat <<< '
-                  {
-                    "apiVersion": "authentication.k8s.io/v1beta1",
-                    "kind": "TokenReview",
-                    "metadata": {
-                        "creationTimestamp": null
-                    },
-                    "spec": {
-                        "token": "'$(openstack token issue -f value -c id)'"
-                    }
-                  }' | curl -kvs -XPOST -d @- https://localhost:8443/webhook | python -c "import sys, json; print json.load(sys.stdin)"
-              )
-              base_body=$(cat <<< '
-                  {
-                      "apiVersion": "authorization.k8s.io/v1beta1",
-                      "kind": "SubjectAccessReview",
-                      "spec": {
-                          "resourceAttributes": {
-                              "namespace": "default",
-                              "verb": "get",
-                              "group": "",
-                              "resource": "pods"
-                          }
-                      }
-                  }' |  python -c "import sys, json; print json.load(sys.stdin)"
-              )
-              update_auth_info=$(echo "
-                  import json;
-                  s1=$authenticated_info;
-                  s2=$base_body;
-                  s2['spec']['user']=s1['status']['user']['username'];
-                  s2['spec']['group']=s1['status']['user']['groups'];
-                  s2['spec']['extra']=s1['status']['user']['extra'];
-                  print json.dumps(s2)" | sed 's/^ \+//'
-              )
-              authorization_body=$(python -c "$update_auth_info")
-              allowed=$(echo "$authorization_body" | curl -kvs -XPOST -d @- https://localhost:8443/webhook | python -mjson.tool)
-          } > /dev/null 2>&1
-
-          echo "$allowed"
-          [[ "$allowed" =~ '"allowed": true' ]] && echo "Testing k8s-keystone-auth sucessfully!"
-
-          # NOTE: k8s+keystone webhook test case need the OS_DOMAIN_NAME env
-          export OS_DOMAIN_NAME=Default
-          '{{ kubectl }}' config set-credentials openstackuser --auth-provider=openstack
-          '{{ kubectl }}' config set-context --cluster=local --user=openstackuser openstackuser@local
-          '{{ kubectl }}' config use-context openstackuser@local
-          if ! '{{ kubectl }}' get pods; then
-              echo "Testing kubernetes+keystone authentication and authorization failed!"
-              exit 1
-          fi
+          kubectl create clusterrolebinding --user system:serviceaccount:kube-system:default kube-system-cluster-admin-1 --clusterrole cluster-admin
+          kubectl create clusterrolebinding --user system:serviceaccount:kube-system:pvl-controller kube-system-cluster-admin-2 --clusterrole cluster-admin
+          kubectl create clusterrolebinding --user system:serviceaccount:kube-system:cloud-node-controller kube-system-cluster-admin-3 --clusterrole cluster-admin
+          kubectl create clusterrolebinding --user system:serviceaccount:kube-system:cloud-controller-manager kube-system-cluster-admin-4 --clusterrole cluster-admin
+          kubectl create clusterrolebinding --user system:serviceaccount:kube-system:shared-informers kube-system-cluster-admin-5 --clusterrole cluster-admin
+          kubectl create clusterrolebinding --user system:kube-controller-manager kube-system-cluster-admin-6 --clusterrole cluster-admin
         executable: /bin/bash
         chdir: '{{ k8s_os_provider_src_dir }}'
       environment: '{{ global_env }}'
+
+    - name: Add openstack user context
+      blockinfile:
+        path: "{{ ansible_user_dir }}/.kube/.kube/config"
+        insertafter: "users:"
+        block: |
+          - name: openstactokenkuser
+            user:
+              exec:
+                command: /bin/bash
+                apiVersion: client.authentication.k8s.io/v1alpha1
+                args:
+                - -c
+                - >
+                  if [ -z ${OS_TOKEN} ]; then
+                      echo 'Error: Missing OpenStack credential from environment variable $OS_TOKEN' > /dev/stderr
+                      exit 1
+                  else
+                      echo '{ "apiVersion": "client.authentication.k8s.io/v1alpha1", "kind": "ExecCredential", "status": { "token": "'"${OS_TOKEN}"'"}}'
+                  fi
+
+    - name: Run e2e tests for k8s-keystone-auth webhook
+      shell:
+        executable: /bin/bash
+        chdir: '{{ k8s_os_provider_src_dir }}'
+        cmd: |
+          source /opt/stack/new/devstack/openrc demo demo > /dev/null
+
+          # The default Keystone token expiration time in devstack is 3 hours.
+          token=$(openstack token issue -f yaml -c id | awk '{print $2}')
+          export OS_TOKEN=$token
+          kubectl config set-context openstack --cluster local --user openstactokenkuser --kubeconfig {{ ansible_user_dir }}/.kube/.kube/config
+
+          OS_TOKEN=$token OS_CONTEXT_NAME=openstack AUTH_POLICY_CONFIGMAP=keystone-auth-policy ROLE_MAPPING_CONFIGMAP=keystone-sync-policy tests/e2e/k8s-keystone-auth/test-authz.sh
